import { useNavigate } from "react-router-dom";

export default function Terms() {
    const navigate = useNavigate();
    return (
        <div style={{ maxWidth: "800px", margin: "0 auto", padding: "40px 20px", color: "var(--text-color)", overflowY: "auto", height: "100%", boxSizing: "border-box" }}>
            <h1 style={{ marginBottom: "2rem" }}>Terms and Conditions</h1>

            <section style={{ marginBottom: "2rem" }}>
                <h2 style={{ fontSize: "1.3rem", borderBottom: "1px solid var(--border-color)", paddingBottom: "0.5rem", marginBottom: "1rem" }}>
                    1. AI Mind Palace Personal Use License
                </h2>
                <p style={{ lineHeight: 1.6, opacity: 0.9 }}>
                    By using AI Mind Palace ("the Software"), you agree to be bound by the terms of the AI Mind Palace Personal Use License.
                    The Software is provided free of charge for personal and educational use.
                </p>
            </section>

            <section style={{ marginBottom: "2rem" }}>
                <h2 style={{ fontSize: "1.3rem", borderBottom: "1px solid var(--border-color)", paddingBottom: "0.5rem", marginBottom: "1rem" }}>
                    2. Attribution
                </h2>
                <p style={{ lineHeight: 1.6, opacity: 0.9 }}>
                    Proper credit must be given to the original author (Pratham Jaiswal), including the name and <a href="https://github.com/pratham-jaiswal/ai-mind-palace" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--text-color)' }}>project link</a> in all forks, modifications, and redistributions.
                </p>
            </section>

            <section style={{ marginBottom: "2rem" }}>
                <h2 style={{ fontSize: "1.3rem", borderBottom: "1px solid var(--border-color)", paddingBottom: "0.5rem", marginBottom: "1rem" }}>
                    3. Non-Commercial Use
                </h2>
                <p style={{ lineHeight: 1.6, opacity: 0.9 }}>
                    The Software may not be used, in whole or in part, for commercial purposes of any kind. For commercial licensing inquiries or to purchase a license for business use, please contact the repository owner.
                </p>
            </section>

            <section style={{ marginBottom: "2rem" }}>
                <h2 style={{ fontSize: "1.3rem", borderBottom: "1px solid var(--border-color)", paddingBottom: "0.5rem", marginBottom: "1rem" }}>
                    4. Warranty Disclaimer
                </h2>
                <p style={{ lineHeight: 1.6, opacity: 0.9 }}>
                    The Software is provided "as is", without warranty of any kind. This includes but is not limited to the performance, availability, and accuracy of any associated AI models (such as OpenAI, Gemini, or Groq) linked through the Software's endpoints.
                    <br /><br />
                    <strong>AI can make mistakes.</strong> You are solely responsible for verifying important information generated by the AI agent before relying upon it.
                </p>
            </section>

            <div style={{ marginTop: "3rem", textAlign: "center" }}>
                <button onClick={() => navigate(-1)} style={{ background: "none", border: "none", cursor: "pointer", color: "var(--subtext-color)", textDecoration: "none", opacity: 0.8, fontSize: "0.9rem", padding: 0 }}>&larr; Go Back</button>
            </div>
        </div>
    );
}
